///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ContactModelCustomer {
/*
{
  "customer_id": 20005516,
  "email": "sapio676@gmail.com",
  "phone_number": "",
  "phone_number_2": "",
  "is_show_warehouse_air": false,
  "is_show_warehouse_sea": false,
  "avatar": "https://devapi.blueraycargo.id/static/images/no-image.jpg",
  "membership_almost_expired": false,
  "company": "",
  "id_card_validation": "",
  "is_allow_china": true,
  "created_at": "2025-04-15T09:15:39.119562+07:00",
  "updated_at": "2025-04-15T09:16:36.527616+07:00",
  "deleted_at": "",
  "username": "",
  "first_name": "Yanto",
  "last_name": "Kurniawan",
  "gender": "",
  "birth_place": "",
  "birthday": "",
  "nationality": "",
  "marketer": "",
  "id_card_number": "",
  "id_card_image": "",
  "id_card_name": "",
  "id_card_address": "",
  "id_card_validation_status": "unverified",
  "status": "incomplete-data",
  "customer_type": "regular",
  "referral_code": "",
  "is_company_customer": false,
  "is_pph_customer": false,
  "register_code": "R6R63A",
  "google_id": "",
  "google_link": "",
  "facebook_id": "",
  "facebook_link": "",
  "apple_id": "",
  "status_paylater": "",
  "paylater_used": 0,
  "paylater_limit": 0,
  "status_payonarrival": "unverified",
  "membership_type": "basic",
  "membership_saldo": 0,
  "membership_expiry_date": "",
  "is_show_showcase": true,
  "is_have_transaction": false,
  "additional_json": "",
  "additional_json2": "",
  "nurturer_tag": "",
  "sales_tag": "",
  "sales_tag_air": "",
  "sales_tag_sea": ""
} 
*/

  int? customerId;
  String? email;
  String? phoneNumber;
  String? phoneNumber_2;
  bool? isShowWarehouseAir;
  bool? isShowWarehouseSea;
  String? avatar;
  bool? membershipAlmostExpired;
  String? company;
  String? idCardValidation;
  bool? isAllowChina;
  String? createdAt;
  String? updatedAt;
  String? deletedAt;
  String? username;
  String? firstName;
  String? lastName;
  String? gender;
  String? birthPlace;
  String? birthday;
  String? nationality;
  String? marketer;
  String? idCardNumber;
  String? idCardImage;
  String? idCardName;
  String? idCardAddress;
  String? idCardValidationStatus;
  String? status;
  String? customerType;
  String? referralCode;
  bool? isCompanyCustomer;
  bool? isPphCustomer;
  String? registerCode;
  String? googleId;
  String? googleLink;
  String? facebookId;
  String? facebookLink;
  String? appleId;
  String? statusPaylater;
  int? paylaterUsed;
  int? paylaterLimit;
  String? statusPayonarrival;
  String? membershipType;
  int? membershipSaldo;
  String? membershipExpiryDate;
  bool? isShowShowcase;
  bool? isHaveTransaction;
  String? additionalJson;
  String? additionalJson2;
  String? nurturerTag;
  String? salesTag;
  String? salesTagAir;
  String? salesTagSea;

  ContactModelCustomer({
    this.customerId,
    this.email,
    this.phoneNumber,
    this.phoneNumber_2,
    this.isShowWarehouseAir,
    this.isShowWarehouseSea,
    this.avatar,
    this.membershipAlmostExpired,
    this.company,
    this.idCardValidation,
    this.isAllowChina,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
    this.username,
    this.firstName,
    this.lastName,
    this.gender,
    this.birthPlace,
    this.birthday,
    this.nationality,
    this.marketer,
    this.idCardNumber,
    this.idCardImage,
    this.idCardName,
    this.idCardAddress,
    this.idCardValidationStatus,
    this.status,
    this.customerType,
    this.referralCode,
    this.isCompanyCustomer,
    this.isPphCustomer,
    this.registerCode,
    this.googleId,
    this.googleLink,
    this.facebookId,
    this.facebookLink,
    this.appleId,
    this.statusPaylater,
    this.paylaterUsed,
    this.paylaterLimit,
    this.statusPayonarrival,
    this.membershipType,
    this.membershipSaldo,
    this.membershipExpiryDate,
    this.isShowShowcase,
    this.isHaveTransaction,
    this.additionalJson,
    this.additionalJson2,
    this.nurturerTag,
    this.salesTag,
    this.salesTagAir,
    this.salesTagSea,
  });
  ContactModelCustomer.fromJson(Map<String, dynamic> json) {
    customerId = json['customer_id']?.toInt();
    email = json['email']?.toString();
    phoneNumber = json['phone_number']?.toString();
    phoneNumber_2 = json['phone_number_2']?.toString();
    isShowWarehouseAir = json['is_show_warehouse_air'];
    isShowWarehouseSea = json['is_show_warehouse_sea'];
    avatar = json['avatar']?.toString();
    membershipAlmostExpired = json['membership_almost_expired'];
    company = json['company']?.toString();
    idCardValidation = json['id_card_validation']?.toString();
    isAllowChina = json['is_allow_china'];
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    deletedAt = json['deleted_at']?.toString();
    username = json['username']?.toString();
    firstName = json['first_name']?.toString();
    lastName = json['last_name']?.toString();
    gender = json['gender']?.toString();
    birthPlace = json['birth_place']?.toString();
    birthday = json['birthday']?.toString();
    nationality = json['nationality']?.toString();
    marketer = json['marketer']?.toString();
    idCardNumber = json['id_card_number']?.toString();
    idCardImage = json['id_card_image']?.toString();
    idCardName = json['id_card_name']?.toString();
    idCardAddress = json['id_card_address']?.toString();
    idCardValidationStatus = json['id_card_validation_status']?.toString();
    status = json['status']?.toString();
    customerType = json['customer_type']?.toString();
    referralCode = json['referral_code']?.toString();
    isCompanyCustomer = json['is_company_customer'];
    isPphCustomer = json['is_pph_customer'];
    registerCode = json['register_code']?.toString();
    googleId = json['google_id']?.toString();
    googleLink = json['google_link']?.toString();
    facebookId = json['facebook_id']?.toString();
    facebookLink = json['facebook_link']?.toString();
    appleId = json['apple_id']?.toString();
    statusPaylater = json['status_paylater']?.toString();
    paylaterUsed = json['paylater_used']?.toInt();
    paylaterLimit = json['paylater_limit']?.toInt();
    statusPayonarrival = json['status_payonarrival']?.toString();
    membershipType = json['membership_type']?.toString();
    membershipSaldo = json['membership_saldo']?.toInt();
    membershipExpiryDate = json['membership_expiry_date']?.toString();
    isShowShowcase = json['is_show_showcase'];
    isHaveTransaction = json['is_have_transaction'];
    additionalJson = json['additional_json']?.toString();
    additionalJson2 = json['additional_json2']?.toString();
    nurturerTag = json['nurturer_tag']?.toString();
    salesTag = json['sales_tag']?.toString();
    salesTagAir = json['sales_tag_air']?.toString();
    salesTagSea = json['sales_tag_sea']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['customer_id'] = customerId;
    data['email'] = email;
    data['phone_number'] = phoneNumber;
    data['phone_number_2'] = phoneNumber_2;
    data['is_show_warehouse_air'] = isShowWarehouseAir;
    data['is_show_warehouse_sea'] = isShowWarehouseSea;
    data['avatar'] = avatar;
    data['membership_almost_expired'] = membershipAlmostExpired;
    data['company'] = company;
    data['id_card_validation'] = idCardValidation;
    data['is_allow_china'] = isAllowChina;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    data['deleted_at'] = deletedAt;
    data['username'] = username;
    data['first_name'] = firstName;
    data['last_name'] = lastName;
    data['gender'] = gender;
    data['birth_place'] = birthPlace;
    data['birthday'] = birthday;
    data['nationality'] = nationality;
    data['marketer'] = marketer;
    data['id_card_number'] = idCardNumber;
    data['id_card_image'] = idCardImage;
    data['id_card_name'] = idCardName;
    data['id_card_address'] = idCardAddress;
    data['id_card_validation_status'] = idCardValidationStatus;
    data['status'] = status;
    data['customer_type'] = customerType;
    data['referral_code'] = referralCode;
    data['is_company_customer'] = isCompanyCustomer;
    data['is_pph_customer'] = isPphCustomer;
    data['register_code'] = registerCode;
    data['google_id'] = googleId;
    data['google_link'] = googleLink;
    data['facebook_id'] = facebookId;
    data['facebook_link'] = facebookLink;
    data['apple_id'] = appleId;
    data['status_paylater'] = statusPaylater;
    data['paylater_used'] = paylaterUsed;
    data['paylater_limit'] = paylaterLimit;
    data['status_payonarrival'] = statusPayonarrival;
    data['membership_type'] = membershipType;
    data['membership_saldo'] = membershipSaldo;
    data['membership_expiry_date'] = membershipExpiryDate;
    data['is_show_showcase'] = isShowShowcase;
    data['is_have_transaction'] = isHaveTransaction;
    data['additional_json'] = additionalJson;
    data['additional_json2'] = additionalJson2;
    data['nurturer_tag'] = nurturerTag;
    data['sales_tag'] = salesTag;
    data['sales_tag_air'] = salesTagAir;
    data['sales_tag_sea'] = salesTagSea;
    return data;
  }
}

class ContactModel {
/*
{
  "action": true,
  "message": "Customer successfully registered",
  "customer": {
    "customer_id": 20005516,
    "email": "sapio676@gmail.com",
    "phone_number": "",
    "phone_number_2": "",
    "is_show_warehouse_air": false,
    "is_show_warehouse_sea": false,
    "avatar": "https://devapi.blueraycargo.id/static/images/no-image.jpg",
    "membership_almost_expired": false,
    "company": "",
    "id_card_validation": "",
    "is_allow_china": true,
    "created_at": "2025-04-15T09:15:39.119562+07:00",
    "updated_at": "2025-04-15T09:16:36.527616+07:00",
    "deleted_at": "",
    "username": "",
    "first_name": "Yanto",
    "last_name": "Kurniawan",
    "gender": "",
    "birth_place": "",
    "birthday": "",
    "nationality": "",
    "marketer": "",
    "id_card_number": "",
    "id_card_image": "",
    "id_card_name": "",
    "id_card_address": "",
    "id_card_validation_status": "unverified",
    "status": "incomplete-data",
    "customer_type": "regular",
    "referral_code": "",
    "is_company_customer": false,
    "is_pph_customer": false,
    "register_code": "R6R63A",
    "google_id": "",
    "google_link": "",
    "facebook_id": "",
    "facebook_link": "",
    "apple_id": "",
    "status_paylater": "",
    "paylater_used": 0,
    "paylater_limit": 0,
    "status_payonarrival": "unverified",
    "membership_type": "basic",
    "membership_saldo": 0,
    "membership_expiry_date": "",
    "is_show_showcase": true,
    "is_have_transaction": false,
    "additional_json": "",
    "additional_json2": "",
    "nurturer_tag": "",
    "sales_tag": "",
    "sales_tag_air": "",
    "sales_tag_sea": ""
  }
} 
*/

  bool? action;
  String? message;
  ContactModelCustomer? customer;

  ContactModel({
    this.action,
    this.message,
    this.customer,
  });
  ContactModel.fromJson(Map<String, dynamic> json) {
    action = json['action'];
    message = json['message']?.toString();
    customer = (json['customer'] != null) ? ContactModelCustomer.fromJson(json['customer']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['action'] = action;
    data['message'] = message;
    if (customer != null) {
      data['customer'] = customer!.toJson();
    }
    return data;
  }
}

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ErrorContactModel {
  /*
{
  "action": false,
  "message": "dimas@admin.com sudah pernah digunakan"
} 
*/

  bool? action;
  String? message;

  ErrorContactModel({this.action, this.message});
  ErrorContactModel.fromJson(Map<String, dynamic> json) {
    action = json['action'];
    message = json['message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['action'] = action;
    data['message'] = message;
    return data;
  }
}
