///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class RegisterModel {
  /*
{
  "action": true,
  "message": "New user registration  is successful",
  "status": 201
} 
*/

  bool? action;
  String? message;
  int? status;

  RegisterModel({this.action, this.message, this.status});
  RegisterModel.fromJson(Map<String, dynamic> json) {
    action = json['action'];
    message = json['message']?.toString();
    status = json['status']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['action'] = action;
    data['message'] = message;
    data['status'] = status;
    return data;
  }
}

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ErrorRegisterModel {
  /*
{
  "message": "Customer dengan email/blueray/no telp email@yahoo.com sudah terdaftar melalui Blueray Cargo",
  "register_origin": "blueray",
  "action": false
} 
*/

  String? message;
  String? registerOrigin;
  bool? action;

  ErrorRegisterModel({this.message, this.registerOrigin, this.action});
  ErrorRegisterModel.fromJson(Map<String, dynamic> json) {
    message = json['message']?.toString();
    registerOrigin = json['register_origin']?.toString();
    action = json['action'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['message'] = message;
    data['register_origin'] = registerOrigin;
    data['action'] = action;
    return data;
  }
}
