///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ResendCodeModel {
  /*
{
  "action": true,
  "message": "Resend registration code is success, check your code at mc903hv7bh@jxpomup.com"
} 
*/

  bool? action;
  String? message;

  ResendCodeModel({this.action, this.message});
  ResendCodeModel.fromJson(Map<String, dynamic> json) {
    action = json['action'];
    message = json['message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['action'] = action;
    data['message'] = message;
    return data;
  }
}
