///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class VerificationModel {
  /*
{
  "action": true,
  "message": "Register code is valid."
} 
*/

  bool? action;
  String? message;

  VerificationModel({this.action, this.message});
  VerificationModel.fromJson(Map<String, dynamic> json) {
    action = json['action'];
    message = json['message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['action'] = action;
    data['message'] = message;
    return data;
  }
}
