///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class AddAddressModelResult {
  /*
{
  "address_id": 535,
  "province_id": 21,
  "province_name": "NAD",
  "district_id": 264,
  "district_name": "Gayo Lues",
  "sub_district_id": 337,
  "sub_district_name": "Wonosari",
  "city_code": "TNCJOG20500",
  "npwp_file": "https://dev-assets.blueraycargo.id/assets/202504/55d18409395c4637bad6f8a6df2d6075-young-smiling-man-avatar-brown-600nw-2261401207.webp",
  "created_at": "2025-04-16T20:50:24.323322+07:00",
  "updated_at": "2025-04-16T20:50:24.325885+07:00",
  "deleted_at": "",
  "service": "impor",
  "address_type": "recipient",
  "address_label": "Rumah Asli",
  "name": "Rumah Ku Yang Ini",
  "country_name": "Indonesia",
  "address": "Jl. Mangga Besar VIII No. 12D, Taman Sari",
  "postal_code": "11150",
  "long": 106.816861,
  "lat": -6.1500077,
  "address_map": "Taman Sari, West Jakarta City, Jakarta, Indonesia",
  "email": "muh.ashil@yahoo.com",
  "phone_number": "081122334455",
  "phone_number_2": "",
  "npwp": "1234567812",
  "is_primary": false,
  "note": "",
  "customer": 20005516,
  "province": 21,
  "district": 264,
  "sub_district": 337,
  "country": 82
} 
*/

  int? addressId;
  int? provinceId;
  String? provinceName;
  int? districtId;
  String? districtName;
  int? subDistrictId;
  String? subDistrictName;
  String? cityCode;
  String? npwpFile;
  String? createdAt;
  String? updatedAt;
  String? deletedAt;
  String? service;
  String? addressType;
  String? addressLabel;
  String? name;
  String? countryName;
  String? address;
  String? postalCode;
  double? long;
  double? lat;
  String? addressMap;
  String? email;
  String? phoneNumber;
  String? phoneNumber_2;
  String? npwp;
  bool? isPrimary;
  String? note;
  int? customer;
  int? province;
  int? district;
  int? subDistrict;
  int? country;

  AddAddressModelResult({
    this.addressId,
    this.provinceId,
    this.provinceName,
    this.districtId,
    this.districtName,
    this.subDistrictId,
    this.subDistrictName,
    this.cityCode,
    this.npwpFile,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
    this.service,
    this.addressType,
    this.addressLabel,
    this.name,
    this.countryName,
    this.address,
    this.postalCode,
    this.long,
    this.lat,
    this.addressMap,
    this.email,
    this.phoneNumber,
    this.phoneNumber_2,
    this.npwp,
    this.isPrimary,
    this.note,
    this.customer,
    this.province,
    this.district,
    this.subDistrict,
    this.country,
  });
  AddAddressModelResult.fromJson(Map<String, dynamic> json) {
    addressId = json['address_id']?.toInt();
    provinceId = json['province_id']?.toInt();
    provinceName = json['province_name']?.toString();
    districtId = json['district_id']?.toInt();
    districtName = json['district_name']?.toString();
    subDistrictId = json['sub_district_id']?.toInt();
    subDistrictName = json['sub_district_name']?.toString();
    cityCode = json['city_code']?.toString();
    npwpFile = json['npwp_file']?.toString();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    deletedAt = json['deleted_at']?.toString();
    service = json['service']?.toString();
    addressType = json['address_type']?.toString();
    addressLabel = json['address_label']?.toString();
    name = json['name']?.toString();
    countryName = json['country_name']?.toString();
    address = json['address']?.toString();
    postalCode = json['postal_code']?.toString();
    long = json['long']?.toDouble();
    lat = json['lat']?.toDouble();
    addressMap = json['address_map']?.toString();
    email = json['email']?.toString();
    phoneNumber = json['phone_number']?.toString();
    phoneNumber_2 = json['phone_number_2']?.toString();
    npwp = json['npwp']?.toString();
    isPrimary = json['is_primary'];
    note = json['note']?.toString();
    customer = json['customer']?.toInt();
    province = json['province']?.toInt();
    district = json['district']?.toInt();
    subDistrict = json['sub_district']?.toInt();
    country = json['country']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['address_id'] = addressId;
    data['province_id'] = provinceId;
    data['province_name'] = provinceName;
    data['district_id'] = districtId;
    data['district_name'] = districtName;
    data['sub_district_id'] = subDistrictId;
    data['sub_district_name'] = subDistrictName;
    data['city_code'] = cityCode;
    data['npwp_file'] = npwpFile;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    data['deleted_at'] = deletedAt;
    data['service'] = service;
    data['address_type'] = addressType;
    data['address_label'] = addressLabel;
    data['name'] = name;
    data['country_name'] = countryName;
    data['address'] = address;
    data['postal_code'] = postalCode;
    data['long'] = long;
    data['lat'] = lat;
    data['address_map'] = addressMap;
    data['email'] = email;
    data['phone_number'] = phoneNumber;
    data['phone_number_2'] = phoneNumber_2;
    data['npwp'] = npwp;
    data['is_primary'] = isPrimary;
    data['note'] = note;
    data['customer'] = customer;
    data['province'] = province;
    data['district'] = district;
    data['sub_district'] = subDistrict;
    data['country'] = country;
    return data;
  }
}

class AddAddressModel {
  /*
{
  "action": true,
  "message": "Tambah alamat berhasil dilakukan",
  "status_code": 201,
  "result": {
    "address_id": 535,
    "province_id": 21,
    "province_name": "NAD",
    "district_id": 264,
    "district_name": "Gayo Lues",
    "sub_district_id": 337,
    "sub_district_name": "Wonosari",
    "city_code": "TNCJOG20500",
    "npwp_file": "https://dev-assets.blueraycargo.id/assets/202504/55d18409395c4637bad6f8a6df2d6075-young-smiling-man-avatar-brown-600nw-2261401207.webp",
    "created_at": "2025-04-16T20:50:24.323322+07:00",
    "updated_at": "2025-04-16T20:50:24.325885+07:00",
    "deleted_at": "",
    "service": "impor",
    "address_type": "recipient",
    "address_label": "Rumah Asli",
    "name": "Rumah Ku Yang Ini",
    "country_name": "Indonesia",
    "address": "Jl. Mangga Besar VIII No. 12D, Taman Sari",
    "postal_code": "11150",
    "long": 106.816861,
    "lat": -6.1500077,
    "address_map": "Taman Sari, West Jakarta City, Jakarta, Indonesia",
    "email": "muh.ashil@yahoo.com",
    "phone_number": "081122334455",
    "phone_number_2": "",
    "npwp": "1234567812",
    "is_primary": false,
    "note": "",
    "customer": 20005516,
    "province": 21,
    "district": 264,
    "sub_district": 337,
    "country": 82
  }
} 
*/

  bool? action;
  String? message;
  int? statusCode;
  AddAddressModelResult? result;

  AddAddressModel({this.action, this.message, this.statusCode, this.result});
  AddAddressModel.fromJson(Map<String, dynamic> json) {
    action = json['action'];
    message = json['message']?.toString();
    statusCode = json['status_code']?.toInt();
    result =
        (json['result'] != null)
            ? AddAddressModelResult.fromJson(json['result'])
            : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['action'] = action;
    data['message'] = message;
    data['status_code'] = statusCode;
    if (result != null) {
      data['result'] = result!.toJson();
    }
    return data;
  }
}
