///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class EditAddressModelResult {
  /*
{
  "address_id": 317,
  "province_id": 16,
  "province_name": "KALIMANTAN UTARA",
  "district_id": 40,
  "district_name": "Jakarta Barat",
  "sub_district_id": 32,
  "sub_district_name": "Mendoyo",
  "city_code": "TNCDPS20402",
  "npwp_file": "",
  "created_at": "2024-01-03T09:16:31.999652+07:00",
  "updated_at": "2024-01-04T15:02:35.167235+07:00",
  "deleted_at": "",
  "service": "impor",
  "address_type": "recipient",
  "address_label": "INI TEST EDIT ALAMAT INDONESIA",
  "name": "INI TEST EDIT ALAMAT INDONESIA",
  "country_name": "Indonesia",
  "address": "Jl. Big Manggo VIII No. 12D, Sari Park",
  "postal_code": "918146",
  "long": 106.816861,
  "lat": -6.1500077,
  "address_map": "Taman Sari, West Jakarta City, Jakarta, Indonesia",
  "email": "",
  "phone_number": "087717262810",
  "phone_number_2": "",
  "npwp": "",
  "is_primary": false,
  "note": "",
  "road_name": "",
  "block_number": "",
  "building_name": "",
  "customer": 431,
  "province": 16,
  "district": 40,
  "sub_district": 32,
  "country": 82
} 
*/

  int? addressId;
  int? provinceId;
  String? provinceName;
  int? districtId;
  String? districtName;
  int? subDistrictId;
  String? subDistrictName;
  String? cityCode;
  String? npwpFile;
  String? createdAt;
  String? updatedAt;
  String? deletedAt;
  String? service;
  String? addressType;
  String? addressLabel;
  String? name;
  String? countryName;
  String? address;
  String? postalCode;
  double? long;
  double? lat;
  String? addressMap;
  String? email;
  String? phoneNumber;
  String? phoneNumber_2;
  String? npwp;
  bool? isPrimary;
  String? note;
  String? roadName;
  String? blockNumber;
  String? buildingName;
  int? customer;
  int? province;
  int? district;
  int? subDistrict;
  int? country;

  EditAddressModelResult({
    this.addressId,
    this.provinceId,
    this.provinceName,
    this.districtId,
    this.districtName,
    this.subDistrictId,
    this.subDistrictName,
    this.cityCode,
    this.npwpFile,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
    this.service,
    this.addressType,
    this.addressLabel,
    this.name,
    this.countryName,
    this.address,
    this.postalCode,
    this.long,
    this.lat,
    this.addressMap,
    this.email,
    this.phoneNumber,
    this.phoneNumber_2,
    this.npwp,
    this.isPrimary,
    this.note,
    this.roadName,
    this.blockNumber,
    this.buildingName,
    this.customer,
    this.province,
    this.district,
    this.subDistrict,
    this.country,
  });
  EditAddressModelResult.fromJson(Map<String, dynamic> json) {
    addressId = json['address_id']?.toInt();
    provinceId = json['province_id']?.toInt();
    provinceName = json['province_name']?.toString();
    districtId = json['district_id']?.toInt();
    districtName = json['district_name']?.toString();
    subDistrictId = json['sub_district_id']?.toInt();
    subDistrictName = json['sub_district_name']?.toString();
    cityCode = json['city_code']?.toString();
    npwpFile = json['npwp_file']?.toString();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    deletedAt = json['deleted_at']?.toString();
    service = json['service']?.toString();
    addressType = json['address_type']?.toString();
    addressLabel = json['address_label']?.toString();
    name = json['name']?.toString();
    countryName = json['country_name']?.toString();
    address = json['address']?.toString();
    postalCode = json['postal_code']?.toString();
    long = json['long']?.toDouble();
    lat = json['lat']?.toDouble();
    addressMap = json['address_map']?.toString();
    email = json['email']?.toString();
    phoneNumber = json['phone_number']?.toString();
    phoneNumber_2 = json['phone_number_2']?.toString();
    npwp = json['npwp']?.toString();
    isPrimary = json['is_primary'];
    note = json['note']?.toString();
    roadName = json['road_name']?.toString();
    blockNumber = json['block_number']?.toString();
    buildingName = json['building_name']?.toString();
    customer = json['customer']?.toInt();
    province = json['province']?.toInt();
    district = json['district']?.toInt();
    subDistrict = json['sub_district']?.toInt();
    country = json['country']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['address_id'] = addressId;
    data['province_id'] = provinceId;
    data['province_name'] = provinceName;
    data['district_id'] = districtId;
    data['district_name'] = districtName;
    data['sub_district_id'] = subDistrictId;
    data['sub_district_name'] = subDistrictName;
    data['city_code'] = cityCode;
    data['npwp_file'] = npwpFile;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    data['deleted_at'] = deletedAt;
    data['service'] = service;
    data['address_type'] = addressType;
    data['address_label'] = addressLabel;
    data['name'] = name;
    data['country_name'] = countryName;
    data['address'] = address;
    data['postal_code'] = postalCode;
    data['long'] = long;
    data['lat'] = lat;
    data['address_map'] = addressMap;
    data['email'] = email;
    data['phone_number'] = phoneNumber;
    data['phone_number_2'] = phoneNumber_2;
    data['npwp'] = npwp;
    data['is_primary'] = isPrimary;
    data['note'] = note;
    data['road_name'] = roadName;
    data['block_number'] = blockNumber;
    data['building_name'] = buildingName;
    data['customer'] = customer;
    data['province'] = province;
    data['district'] = district;
    data['sub_district'] = subDistrict;
    data['country'] = country;
    return data;
  }
}

class EditAddressModel {
  /*
{
  "action": true,
  "message": "successfully Edited address ",
  "result": {
    "address_id": 317,
    "province_id": 16,
    "province_name": "KALIMANTAN UTARA",
    "district_id": 40,
    "district_name": "Jakarta Barat",
    "sub_district_id": 32,
    "sub_district_name": "Mendoyo",
    "city_code": "TNCDPS20402",
    "npwp_file": "",
    "created_at": "2024-01-03T09:16:31.999652+07:00",
    "updated_at": "2024-01-04T15:02:35.167235+07:00",
    "deleted_at": "",
    "service": "impor",
    "address_type": "recipient",
    "address_label": "INI TEST EDIT ALAMAT INDONESIA",
    "name": "INI TEST EDIT ALAMAT INDONESIA",
    "country_name": "Indonesia",
    "address": "Jl. Big Manggo VIII No. 12D, Sari Park",
    "postal_code": "918146",
    "long": 106.816861,
    "lat": -6.1500077,
    "address_map": "Taman Sari, West Jakarta City, Jakarta, Indonesia",
    "email": "",
    "phone_number": "087717262810",
    "phone_number_2": "",
    "npwp": "",
    "is_primary": false,
    "note": "",
    "road_name": "",
    "block_number": "",
    "building_name": "",
    "customer": 431,
    "province": 16,
    "district": 40,
    "sub_district": 32,
    "country": 82
  },
  "status_code": 200
} 
*/

  bool? action;
  String? message;
  EditAddressModelResult? result;
  int? statusCode;

  EditAddressModel({this.action, this.message, this.result, this.statusCode});
  EditAddressModel.fromJson(Map<String, dynamic> json) {
    action = json['action'];
    message = json['message']?.toString();
    result =
        (json['result'] != null)
            ? EditAddressModelResult.fromJson(json['result'])
            : null;
    statusCode = json['status_code']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['action'] = action;
    data['message'] = message;
    if (result != null) {
      data['result'] = result!.toJson();
    }
    data['status_code'] = statusCode;
    return data;
  }
}
