///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ListAddressModel {
  /*
{
  "address_id": 538,
  "province_id": 1,
  "province_name": "BALI",
  "district_id": 6,
  "district_name": "Jembrana",
  "sub_district_id": 32,
  "sub_district_name": "Mendoyo",
  "city_code": "TNCDPS20402",
  "npwp_file": "https://dev-assets.blueraycargo.id/assets/202504/6c2bc1ef025e4e9892cdff9884275e5c-photo_241130071312.jpeg",
  "created_at": "2025-04-16T21:35:37.200966+07:00",
  "updated_at": "2025-04-16T21:35:37.204055+07:00",
  "deleted_at": "",
  "service": "impor",
  "address_type": "recipient",
  "address_label": "Rumah Kita",
  "name": "Yaptu",
  "country_name": "Indonesia",
  "address": "Jl. Gn. Penulisan No.4, Kecamatan Mengwi, 80351, Indonesia",
  "postal_code": "11150",
  "long": 113.4046311,
  "lat": -8.1275482,
  "address_map": "Jl. Gn. Penulisan No.4, Kecamatan Mengwi, 80351, Indonesia",
  "email": "hajg@mail.com",
  "phone_number": "0857946223",
  "phone_number_2": "",
  "npwp": "08616297273",
  "is_primary": false,
  "note": "",
  "customer": 20005516,
  "province": 1,
  "district": 6,
  "sub_district": 32,
  "country": 82
} 
*/

  int? addressId;
  int? provinceId;
  String? provinceName;
  int? districtId;
  String? districtName;
  int? subDistrictId;
  String? subDistrictName;
  String? cityCode;
  String? npwpFile;
  String? createdAt;
  String? updatedAt;
  String? deletedAt;
  String? service;
  String? addressType;
  String? addressLabel;
  String? name;
  String? countryName;
  String? address;
  String? postalCode;
  double? long;
  double? lat;
  String? addressMap;
  String? email;
  String? phoneNumber;
  String? phoneNumber_2;
  String? npwp;
  bool? isPrimary;
  String? note;
  int? customer;
  int? province;
  int? district;
  int? subDistrict;
  int? country;

  ListAddressModel({
    this.addressId,
    this.provinceId,
    this.provinceName,
    this.districtId,
    this.districtName,
    this.subDistrictId,
    this.subDistrictName,
    this.cityCode,
    this.npwpFile,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
    this.service,
    this.addressType,
    this.addressLabel,
    this.name,
    this.countryName,
    this.address,
    this.postalCode,
    this.long,
    this.lat,
    this.addressMap,
    this.email,
    this.phoneNumber,
    this.phoneNumber_2,
    this.npwp,
    this.isPrimary,
    this.note,
    this.customer,
    this.province,
    this.district,
    this.subDistrict,
    this.country,
  });
  ListAddressModel.fromJson(Map<String, dynamic> json) {
    addressId = json['address_id']?.toInt();
    provinceId = json['province_id']?.toInt();
    provinceName = json['province_name']?.toString();
    districtId = json['district_id']?.toInt();
    districtName = json['district_name']?.toString();
    subDistrictId = json['sub_district_id']?.toInt();
    subDistrictName = json['sub_district_name']?.toString();
    cityCode = json['city_code']?.toString();
    npwpFile = json['npwp_file']?.toString();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    deletedAt = json['deleted_at']?.toString();
    service = json['service']?.toString();
    addressType = json['address_type']?.toString();
    addressLabel = json['address_label']?.toString();
    name = json['name']?.toString();
    countryName = json['country_name']?.toString();
    address = json['address']?.toString();
    postalCode = json['postal_code']?.toString();
    long = json['long']?.toDouble();
    lat = json['lat']?.toDouble();
    addressMap = json['address_map']?.toString();
    email = json['email']?.toString();
    phoneNumber = json['phone_number']?.toString();
    phoneNumber_2 = json['phone_number_2']?.toString();
    npwp = json['npwp']?.toString();
    isPrimary = json['is_primary'];
    note = json['note']?.toString();
    customer = json['customer']?.toInt();
    province = json['province']?.toInt();
    district = json['district']?.toInt();
    subDistrict = json['sub_district']?.toInt();
    country = json['country']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['address_id'] = addressId;
    data['province_id'] = provinceId;
    data['province_name'] = provinceName;
    data['district_id'] = districtId;
    data['district_name'] = districtName;
    data['sub_district_id'] = subDistrictId;
    data['sub_district_name'] = subDistrictName;
    data['city_code'] = cityCode;
    data['npwp_file'] = npwpFile;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    data['deleted_at'] = deletedAt;
    data['service'] = service;
    data['address_type'] = addressType;
    data['address_label'] = addressLabel;
    data['name'] = name;
    data['country_name'] = countryName;
    data['address'] = address;
    data['postal_code'] = postalCode;
    data['long'] = long;
    data['lat'] = lat;
    data['address_map'] = addressMap;
    data['email'] = email;
    data['phone_number'] = phoneNumber;
    data['phone_number_2'] = phoneNumber_2;
    data['npwp'] = npwp;
    data['is_primary'] = isPrimary;
    data['note'] = note;
    data['customer'] = customer;
    data['province'] = province;
    data['district'] = district;
    data['sub_district'] = subDistrict;
    data['country'] = country;
    return data;
  }
}
