///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ProvinceModelMeta {
  /*
{
  "administrative_area_level": 1,
  "updated_at": "2024-10-09T16:56:42+00:00"
} 
*/

  int? administrativeAreaLevel;
  String? updatedAt;

  ProvinceModelMeta({this.administrativeAreaLevel, this.updatedAt});
  ProvinceModelMeta.fromJson(Map<String, dynamic> json) {
    administrativeAreaLevel = json['administrative_area_level']?.toInt();
    updatedAt = json['updated_at']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['administrative_area_level'] = administrativeAreaLevel;
    data['updated_at'] = updatedAt;
    return data;
  }
}

class ProvinceModelData {
  /*
{
  "code": "11",
  "name": "Aceh"
} 
*/

  String? code;
  String? name;

  ProvinceModelData({this.code, this.name});
  ProvinceModelData.fromJson(Map<String, dynamic> json) {
    code = json['code']?.toString();
    name = json['name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['code'] = code;
    data['name'] = name;
    return data;
  }
}

class ProvinceModel {
  /*
{
  "data": [
    {
      "code": "11",
      "name": "Aceh"
    }
  ],
  "meta": {
    "administrative_area_level": 1,
    "updated_at": "2024-10-09T16:56:42+00:00"
  }
} 
*/

  List<ProvinceModelData?>? data;
  ProvinceModelMeta? meta;

  ProvinceModel({this.data, this.meta});
  ProvinceModel.fromJson(Map<String, dynamic> json) {
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <ProvinceModelData>[];
      v.forEach((v) {
        arr0.add(ProvinceModelData.fromJson(v));
      });
      this.data = arr0;
    }
    meta =
        (json['meta'] != null)
            ? ProvinceModelMeta.fromJson(json['meta'])
            : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    if (meta != null) {
      data['meta'] = meta!.toJson();
    }
    return data;
  }
}
