///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class UploadModel {
  /*
{
  "action": true,
  "message": "Upload images has been successfully",
  "file_url": "https://dev-assets.blueraycargo.id/assets/202504/55d18409395c4637bad6f8a6df2d6075-young-smiling-man-avatar-brown-600nw-2261401207.webp",
  "content_length": 11520
} 
*/

  bool? action;
  String? message;
  String? fileUrl;
  int? contentLength;

  UploadModel({this.action, this.message, this.fileUrl, this.contentLength});
  UploadModel.fromJson(Map<String, dynamic> json) {
    action = json['action'];
    message = json['message']?.toString();
    fileUrl = json['file_url']?.toString();
    contentLength = json['content_length']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['action'] = action;
    data['message'] = message;
    data['file_url'] = fileUrl;
    data['content_length'] = contentLength;
    return data;
  }
}
